version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
      - ./dbdata/struct:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wscn
 

