version: '3.9'
services:
  linda_news_mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: linda-news-mysql-container
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
      MYSQL_ROOT_HOST: "%"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./dbdata/mysql:/var/lib/mysql
      - ./dbdata/struct:/docker-entrypoint-initdb.d
  linda_news_redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./dbdata/redis:/data


# Login try to with command: docker exec -it linda-trade-mysql-container mysql -u root -p
